addSbtPlugin("com.dwijnand"      % "sbt-dynver"          % "4.1.1")
addSbtPlugin("de.heikoseeberger" % "sbt-header"          % "5.6.0")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"        % "2.4.2")
addSbtPlugin("de.gccc.sbt"       % "sbt-jib"             % "1.0.0")
addSbtPlugin("se.marcuslonnberg" % "sbt-docker"          % "1.9.0")
addSbtPlugin("com.github.sbt"    % "sbt-native-packager" % "1.9.9")
